SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE toss_payment RESTART IDENTITY;
TRUNCATE TABLE payment_session;
TRUNCATE TABLE reservation RESTART IDENTITY;
TRUNCATE TABLE reservation_time RESTART IDENTITY;
TRUNCATE TABLE theme RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
